name: Cypress Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - Pipeline_Activity
  pull_request:

jobs: 
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run dev
          start: pnpm cypress start