name: Cypress Tests

on:
  push:
    branches:
      - main
      - Pipeline_Activity

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    steps:
      name: cypress e2e tests
      uses: cypress-io/github-action@v6
      env:
        CI: true


  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: use node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

  cypress-run:
    runs-on: ubuntu-latest
    needs: setup

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependancies
        run: pnpm install --no-frozen-lockfile

      - name: Run build
        run: npm run build

      - name: Run Cypress
        run: pnpm test:e2e:ci
