name: Cypress Tests

on:
  push:
    branches:
      - main
      - Pipeline_Activity

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: use node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          
      - name: pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

  cypress-run:
    runs-on: ubuntu-latest
    needs: setup

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependancies
        run: pnpm install --no-frozen-lockfile

      - name: Run build
        run: pnpm run build

      - name: Run Cypress
        run: npx cypress run
