name: Cypress Tests

on:
  push:
    branches:
      - main
      - Pipeline_Activity

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm setup
        uses: pnpm/action-setup@v4


  cypress-run:
    runs-on: ubuntu-latest
    needs: setup

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependancies
        run: pnpm install --no-frozen-lockfile

      - name: Run build
        run: pnpm run build

      - name: Run Cypress
        run: npx cypress run
